-- Seed: 14 medical metrics × 2 locales (id-ID, en-US)
-- Sources: AHA 2017, ADA 2023 Standards of Care, WHO, NHLBI/NIH, Mayo Clinic,
--   AASM 2023, ATS 2019, IDF 2023, NICE NG136, EAU 2024

-- ============================================================
-- SpO₂
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('spo2','id-ID','SpO₂','Mengukur saturasi oksigen dalam darah — persentase hemoglobin yang terikat oksigen.','SpO₂ (Saturation of Peripheral Oxygen) mengukur seberapa banyak oksigen dibawa oleh sel darah merah. Nilai ini penting untuk menilai fungsi paru dan jantung. SpO₂ diukur non-invasif melalui sensor cahaya di ujung jari.','Mendeteksi hipoksemia dini sebelum gejala klinis muncul. Penting untuk pasien PPOK, asma, sleep apnea, pasca-COVID, dan kondisi jantung.','Duduk tenang 5 menit. Tangan hangat, tidak bersikat. Sensor di jari telunjuk, tangan setinggi dada. Hindari kutek/cat kuku. Baca setelah angka stabil ±10 detik.','95–100% (dewasa di atas permukaan laut)','Persen (%) = jumlah oksigen terikat per 100 molekul hemoglobin. 97% artinya dari 100 molekul Hb, 97 membawa oksigen.','Oximeter','oximeter','SpO₂ <90%: hipoksemia berat → risiko gagal organ, kerusakan otak. Kronis: pulmonary hypertension, right heart failure.','SpO₂ <92% saat istirahat atau <88% saat aktivitas → segera ke IGD. Perokok: nilai bisa normal meskipun ada COPD (carboxyhemoglobin).','Berhenti merokok. Olahraga teratur untuk kapasitas paru. Vaksinasi influenza dan pneumokokus setiap tahun. Cek SpO₂ jika sesak napas.','WHO Pulse Oximetry Training Manual 2011; ATS Patient Education 2019','https://www.who.int/publications/i/item/9789241501547'),
('spo2','en-US','SpO₂','Measures blood oxygen saturation — the percentage of hemoglobin bound with oxygen.','SpO₂ (Saturation of Peripheral Oxygen) measures how much oxygen is carried by red blood cells. It is vital for assessing lung and heart function. Measured non-invasively via a light sensor on the fingertip.','Detects hypoxemia early before clinical symptoms appear. Essential for COPD, asthma, sleep apnea, post-COVID, and cardiac patients.','Sit quietly for 5 minutes. Warm hands, no nail polish. Sensor on index finger at chest level. Read after number stabilizes for ~10 seconds.','95–100% (adults at sea level)','Percent (%) = molecules of oxygen bound per 100 hemoglobin molecules. 97% means 97 out of 100 Hb molecules carry oxygen.','Pulse Oximeter','oximeter','SpO₂ <90%: severe hypoxemia → organ failure, brain damage risk. Chronic: pulmonary hypertension, right heart failure.','SpO₂ <92% at rest or <88% with exertion → go to ER immediately. Smokers: readings may be falsely normal due to carboxyhemoglobin.','Quit smoking. Exercise regularly for lung capacity. Annual influenza and pneumococcal vaccination. Check SpO₂ if short of breath.','WHO Pulse Oximetry Training Manual 2011; ATS Patient Education 2019','https://www.who.int/publications/i/item/9789241501547');

-- ============================================================
-- Heart Rate
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('heartRate','id-ID','Denyut Jantung','Menghitung jumlah detak jantung per menit — indikator fungsi kardiovaskular dasar.','Denyut jantung (heart rate / pulse) adalah frekuensi kontraksi ventrikel per menit. Mencerminkan kerja jantung, regulasi otonom, dan kebugaran kardiovaskular. Denyut jantung istirahat yang rendah umumnya menandakan kebugaran baik.','Mendeteksi aritmia (fibrilasi atrium, takikardia, bradikardia). Memantau respons obat (beta-blocker, digoxin). Menilai kebugaran dan overtraining.','Duduk/berbaring 5 menit sebelum ukur. Hitung denyut selama 60 detik di nadi radial, atau pakai oximeter/tensimeter. Hindari kafein/rokok 30 menit sebelumnya.','60–100 bpm (dewasa istirahat). Atlet terlatih: 40–60 bpm normal.','bpm = beats per minute (denyut per menit). Menunjukkan seberapa sering jantung berdenyut dalam 1 menit.','Oximeter / Tensimeter','oximeter','Takikardia kronis (>100): risiko stroke, heart failure, takikardiomiopati. Bradikardia (<40 tanpa latihan): sinkope, gagal jantung.','Denyut >150 saat istirahat, <40 tanpa olahraga teratur, atau tidak beraturan (AFib) → segera ke dokter. Gejala: pusing, sesak, nyeri dada.','Olahraga kardio 150 menit/minggu. Batasi kafein <400 mg/hari. Tidur cukup 7–9 jam. Kelola stres. Hindari rokok dan alkohol berlebihan.','AHA Understanding Heart Rate 2023; Mayo Clinic','https://www.heart.org/en/health-topics/high-blood-pressure/the-facts-about-high-blood-pressure/all-about-heart-rate-pulse'),
('heartRate','en-US','Heart Rate','Counts the number of heartbeats per minute — a basic cardiovascular function indicator.','Heart rate (pulse) is the frequency of ventricular contractions per minute. It reflects cardiac workload, autonomic regulation, and cardiovascular fitness. Lower resting heart rate generally indicates better fitness.','Detects arrhythmia (atrial fibrillation, tachycardia, bradycardia). Monitors drug effects (beta-blockers, digoxin). Assesses fitness and overtraining.','Sit/lie down for 5 minutes before measuring. Count pulse for 60 seconds at radial artery, or use oximeter/BP monitor. Avoid caffeine/smoking 30 minutes prior.','60–100 bpm (resting adult). Trained athletes: 40–60 bpm is normal.','bpm = beats per minute. Shows how often the heart beats in 1 minute.','Pulse Oximeter / BP Monitor','oximeter','Chronic tachycardia (>100): stroke, heart failure, tachycardiomyopathy risk. Bradycardia (<40 without training): syncope, heart failure.','HR >150 at rest, <40 without regular exercise, or irregular (AFib) → see doctor immediately. Symptoms: dizziness, shortness of breath, chest pain.','150 min/week cardio exercise. Limit caffeine <400 mg/day. Sleep 7–9 hours. Manage stress. Avoid smoking and excess alcohol.','AHA Understanding Heart Rate 2023; Mayo Clinic','https://www.heart.org/en/health-topics/high-blood-pressure/the-facts-about-high-blood-pressure/all-about-heart-rate-pulse');

-- ============================================================
-- Systolic
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('systolic','id-ID','Tekanan Sistolik','Tekanan darah saat jantung berkontraksi memompa darah ke seluruh tubuh.','Tekanan sistolik adalah tekanan puncak saat ventrikel kiri berkontraksi. Angka ini lebih prediktif terhadap risiko kardiovaskular daripada diastolik, khususnya pada usia >50 tahun (AHA 2017).','Hipertensi adalah silent killer — sering tanpa gejala. Deteksi dini mencegah stroke, serangan jantung, gagal ginjal. Target <130/80 untuk diabetes/CKD (ADA 2023).','Duduk tegak 5 menit. Lengan setinggi jantung. Cuff melingkar rapat di lengan atas. Ukur 2x, ambil rata-rata. Jangan habis kopi/rokok 30 menit sebelumnya.','<120 mmHg = normal; 120–129 = elevated; 130–139 = hipertensi stage 1; ≥140 = hipertensi stage 2 (AHA 2017)','mmHg = millimeter of mercury. 1 mmHg ≈ tekanan 1,36 cmH₂O. Menunjukkan gaya darah pada dinding arteri saat jantung memompa.','Tensimeter','bloodPressure','Sistolik ≥140: risiko stroke 4× lipat, serangan jantung 3× lipat, gagal ginjal kronis. Sistolik >180: krisis hipertensi → kerusakan organ.','Sistolik ≥180 atau <90 dengan gejala (sakit kepala berat, penglihatan kabur, nyeri dada, sesak) → IGD. Sistolik ≥140 tanpa gejala: kontrol ke dokter dalam 1 bulan.','Limit garam <5 g/hari (WHO). Olahraga 150 menit/minggu. Turunkan berat badan jika BMI >25. Batasi alkohol. Kelola stres. Minum obat hipertensi teratur.','AHA 2017 Hypertension Guidelines (Whelton et al.); WHO HEARTS Technical Package','https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings'),
('systolic','en-US','Systolic Pressure','Blood pressure when the heart contracts and pumps blood throughout the body.','Systolic pressure is the peak pressure during left ventricular contraction. It is more predictive of cardiovascular risk than diastolic, especially in adults >50 years (AHA 2017).','Hypertension is a silent killer — often asymptomatic. Early detection prevents stroke, heart attack, kidney failure. Target <130/80 for diabetes/CKD (ADA 2023).','Sit upright for 5 minutes. Arm at heart level. Cuff snug around upper arm. Measure twice, take average. No coffee/smoking 30 minutes prior.','<120 mmHg = normal; 120–129 = elevated; 130–139 = hypertension stage 1; ≥140 = hypertension stage 2 (AHA 2017)','mmHg = millimeters of mercury. 1 mmHg ≈ 1.36 cmH₂O pressure. Indicates force of blood on artery walls when the heart pumps.','Blood Pressure Monitor','bloodPressure','Systolic ≥140: 4× stroke risk, 3× heart attack risk, chronic kidney failure. Systolic >180: hypertensive crisis → organ damage.','Systolic ≥180 or <90 with symptoms (severe headache, blurred vision, chest pain, shortness of breath) → go to ER. Systolic ≥140 without symptoms: see doctor within 1 month.','Limit salt <5 g/day (WHO). Exercise 150 min/week. Lose weight if BMI >25. Limit alcohol. Manage stress. Take hypertension medication regularly.','AHA 2017 Hypertension Guidelines (Whelton et al.); WHO HEARTS Technical Package','https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings');

-- ============================================================
-- Diastolic
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('diastolic','id-ID','Tekanan Diastolik','Tekanan darah saat jantung beristirahat (diastole) antar detikan.','Tekanan diastolik adalah tekanan minimum pada arteri saat jantung mengisi darah. Diastolik tinggi kronis menyebabkan kerusakan pembuluh darah kecil, terutama di ginjal dan otak (NHLBI).','Diastolik tinggi pada usia muda (<50 thn) sama prediktifnya dengan sistolik tinggi terhadap risiko kardiovaskular. Penting untuk skrining hipertensi di usia produktif.','Cara ukur sama dengan sistolik — diukur bersamaan menggunakan tensimeter. Angka bawah dari pembacaan (mis. 120/80 → diastolik = 80).','<80 mmHg = normal; 80–89 = hipertensi stage 1; ≥90 = hipertensi stage 2 (AHA 2017)','mmHg = millimeter raksa. Menunjukkan tekanan minimum di arteri saat jantung istirahat antar detik.','Tensimeter','bloodPressure','Diastolik ≥90 kronis: hipertrofi ventrikel kiri, penyakit ginjal kronis, retinopati hipertensi. Diastolik >120: krisis hipertensi.','Diastolik >120 → segera ke IGD. Diastolik ≥90 + sakit kepala/nystagmus/nosebleed → dokter hari ini. Diastolik ≥80 tanpa gejala: kontrol 3 bulan.','Kurangi garam, proses makanan kalengan/minuman bersoda. Tidur cukup. Jaga berat badan ideal. Cek tekanan darah 6 bulan sekali.','AHA 2017 Hypertension Guidelines; NHLBI/NIH','https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings'),
('diastolic','en-US','Diastolic Pressure','Blood pressure when the heart rests (diastole) between beats.','Diastolic pressure is the minimum pressure in arteries when the heart fills with blood. Chronic high diastolic damages small blood vessels, particularly in kidneys and brain (NHLBI).','High diastolic in younger adults (<50 yr) is equally predictive of cardiovascular risk as high systolic. Important for hypertension screening in working-age adults.','Measured simultaneously with systolic using a BP monitor. The lower number in the reading (e.g., 120/80 → diastolic = 80).','<80 mmHg = normal; 80–89 = hypertension stage 1; ≥90 = hypertension stage 2 (AHA 2017)','mmHg = millimeters of mercury. Indicates minimum pressure in arteries when the heart rests between beats.','Blood Pressure Monitor','bloodPressure','Diastolic ≥90 chronic: left ventricular hypertrophy, chronic kidney disease, hypertensive retinopathy. Diastolic >120: hypertensive crisis.','Diastolic >120 → go to ER immediately. Diastolic ≥90 + headache/nystagmus/nosebleed → see doctor today. Diastolic ≥80 without symptoms: check in 3 months.','Reduce salt, avoid canned/processed food and soda. Adequate sleep. Maintain ideal weight. Check blood pressure every 6 months.','AHA 2017 Hypertension Guidelines; NHLBI/NIH','https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings');

-- ============================================================
-- bloodPressurePulse
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('bloodPressurePulse','id-ID','Pulse Tensimeter','Denyut nadi terbaca oleh tensimeter selama pengukuran tekanan darah.','Pulse tensimeter adalah denyut nadi yang terdeteksi alat saat cuff mengembang dan kempes. Berbeda dari pulse oximeter — ini membaca osilasi dinding arteri, bukan absorpsi cahaya. Berguna untuk cross-check denyut jantung.','Memvalidasi denyut jantung yang terbaca oximeter. Mendeteksi aritmia (jika pulse BP berbeda signifikan dari pulse oximeter → kemungkinan AFib atau PVC).','Otomatis terukur saat tensimeter bekerja. Cocokkan dengan pulse oximeter: jika beda >10 bpm, ulangi pengukuran dan konsultasi dokter.','60–100 bpm (harus konsisten dengan oximeter ±5 bpm)','bpm = denyut per menit via osilasi arteri brachialis. Diukur bersamaan dengan tekanan darah oleh tensimeter digital.','Tensimeter','bloodPressure','Discrepancy >10 bpm dengan oximeter → kemungkinan irregular heartbeat/AFib. Pulse >100 saat istirahat: takikardia.','Jika pulse tensimeter berbeda >15 bpm dari oximeter, atau pulse >120/<40 saat istirahat → periksa EKG ke dokter.','Jaga kebugaran kardiovaskular. Deteksi dini AFib dengan pemantauan rutin. Kurangi stres dan kafein berlebihan.','AHA Understanding Heart Rate; European Heart Rhythm Association 2023','https://www.heart.org/en/health-topics/high-blood-pressure/the-facts-about-high-blood-pressure/all-about-heart-rate-pulse'),
('bloodPressurePulse','en-US','BP Monitor Pulse','Heart rate detected by the blood pressure monitor during measurement.','BP monitor pulse is the heart rate detected by the device as the cuff inflates and deflates. It differs from pulse oximetry — it reads arterial wall oscillations, not light absorption. Useful for cross-checking heart rate.','Validates heart rate from the oximeter. Detects arrhythmia (if BP pulse differs significantly from oximeter pulse → possible AFib or PVC).','Automatically measured when the BP monitor operates. Cross-check with oximeter: if difference >10 bpm, repeat measurement and consult a doctor.','60–100 bpm (should be consistent with oximeter ±5 bpm)','bpm = beats per minute via brachial artery oscillations. Measured simultaneously with blood pressure by digital BP monitor.','Blood Pressure Monitor','bloodPressure','Discrepancy >10 bpm with oximeter → possible irregular heartbeat/AFib. Pulse >100 at rest: tachycardia.','If BP pulse differs >15 bpm from oximeter, or pulse >120/<40 at rest → get ECG from doctor.','Maintain cardiovascular fitness. Early AFib detection with regular monitoring. Reduce stress and excess caffeine.','AHA Understanding Heart Rate; European Heart Rhythm Association 2023','https://www.heart.org/en/health-topics/high-blood-pressure/the-facts-about-high-blood-pressure/all-about-heart-rate-pulse');

-- ============================================================
-- glucoseFasting
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('glucoseFasting','id-ID','Gula Darah Puasa','Kadar glukosa darah setelah puasa 8–12 jam — standar emas skrining diabetes.','Gula darah puasa (Fasting Plasma Glucose / FPG) mengukur glukosa setelah tidak makan minimal 8 jam. Merupakan tes skrining utama diabetes melitus tipe 2 (ADA Standards of Care 2023). Lebih akurat daripada gula darah acak.','Mendeteksi prediabetes dan diabetes dini. 1 dari 3 penderita diabetes tidak tahu mereka terkena (IDF 2023). Semakin dini terdeteksi, semakin efektif pencegahan komplikasi.','Puasa 8–12 jam (hanya air putih). Ukur sebelum makan pagi, idealnya 06.00–09.00. Cuci tangan sebelum tes (sisa makanan di jari bisa mempengaruhi). Gunakan strip yang tidak kedaluwarsa.','70–99 mg/dL = normal; 100–125 = prediabetes; ≥126 = diabetes (ADA 2023)','mg/dL = miligram glukosa per desiliter darah. 100 mg/dL = 100 mg gula dalam 1/10 liter darah. Puasa 8–12 jam memastikan kadar basal, bukan pasca-makan.','GCU (Sinocare)','sinocare','Prediabetes (100–125): 5–10% per tahun berkembang jadi diabetes. Diabetes: retinopati, nefropati, neuropati, penyakit jantung 2–4× lipat.','Gula darah puasa ≥126 mg/dL pada 2 kali tes → diagnosis diabetes → ke dokter. ≥200 mg/dL: segera ke dokter. <70: hipoglikemia → minum jus.','Jaga berat badan ideal. Makanan rendah glikemik index. Olahraga 150 menit/minggu (terbukti turunkan risiko diabetes 58% — DPP study). Hindari minuman manis.','ADA Standards of Medical Care in Diabetes 2023; IDF Diabetes Atlas 2023','https://diabetesjournals.org/care/article/46/Supplement_1/S1/127039/Summary-of-Updates-Standards-of-Care-in-Diabetes'),
('glucoseFasting','en-US','Fasting Blood Glucose','Blood glucose level after fasting 8–12 hours — the gold standard for diabetes screening.','Fasting Plasma Glucose (FPG) measures glucose after not eating for at least 8 hours. It is the primary screening test for type 2 diabetes mellitus (ADA Standards of Care 2023). More accurate than random glucose.','Detects prediabetes and early diabetes. 1 in 3 people with diabetes do not know they have it (IDF 2023). Earlier detection means more effective complication prevention.','Fast 8–12 hours (water only). Measure before breakfast, ideally 6–9 AM. Wash hands before testing (food residue on fingers can affect). Use non-expired strips.','70–99 mg/dL = normal; 100–125 = prediabetes; ≥126 = diabetes (ADA 2023)','mg/dL = milligrams of glucose per deciliter of blood. 100 mg/dL = 100 mg sugar in 1/10 liter of blood. 8–12 hour fasting ensures basal level, not post-meal.','GCU (Sinocare)','sinocare','Prediabetes (100–125): 5–10% per year progress to diabetes. Diabetes: retinopathy, nephropathy, neuropathy, 2–4× heart disease risk.','Fasting glucose ≥126 mg/dL on 2 tests → diabetes diagnosis → see doctor. ≥200 mg/dL: see doctor immediately. <70: hypoglycemia → drink juice.','Maintain ideal weight. Low glycemic index diet. Exercise 150 min/week (proven 58% diabetes risk reduction — DPP study). Avoid sugary drinks.','ADA Standards of Medical Care in Diabetes 2023; IDF Diabetes Atlas 2023','https://diabetesjournals.org/care/article/46/Supplement_1/S1/127039/Summary-of-Updates-Standards-of-Care-in-Diabetes');

-- ============================================================
-- glucosePostMeal
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('glucosePostMeal','id-ID','Gula Darah 2 Jam PP','Kadar glukosa darah 2 jam setelah makan — mengevaluasi respons glikemik.','Gula darah post-prandial (PP) diukur 2 jam setelah makan pertama (dihitung dari awal makan). Merupakan indikator sensitivitas insulin dan toleransi glukosa. ADA 2023: PP ≥200 mg/dL = diabetes.','FPG bisa normal tapi PP tinggi → diabetes terlewat. 30% penderita diabetes hanya terdeteksi lewat tes PP. Penting untuk skrining lengkap dan evaluasi pengobatan.','Ukur tepat 2 jam setelah mulai makan (bukan selesai makan). Makan normal (minimal 75g karbohidrat). Catat waktu mulai makan. Jangan ngemil di antara.','<140 mg/dL = normal; 140–199 = intoleransi glukosa; ≥200 = diabetes (ADA 2023)','mg/dL = miligram glukosa per desiliter darah. Mengukur respons tubuh terhadap asupan karbohidrat. 2 jam PP = saat glukosa seharusnya kembali mendekati baseline.','GCU (Sinocare)','sinocare','PP kronis ≥200: kerusakan pembuluh darah mikro (mata, ginjal, saraf). Risiko kardiovaskular meningkat bahkan di 140–199.','PP ≥200 mg/dL → diagnosis diabetes. PP 140–199 berkali-kali → prediabetes, diskusikan dokter. PP ≥300: bisa terjadi ketoasidosis.','Makan porsi kecil sering (3 besar + 2 selingan). Karbohidrat kompleks lebih baik dari sederhana. Jalan kaki 15 menit setelah makan turunkan PP 30%.','ADA Standards of Care 2023; WHO Definition and Diagnosis of Diabetes','https://diabetesjournals.org/care/article/46/Supplement_1/S1/127039/Summary-of-Updates-Standards-of-Care-in-Diabetes'),
('glucosePostMeal','en-US','Post-Meal Blood Glucose','Blood glucose 2 hours after eating — evaluates glycemic response.','Post-prandial (PP) glucose is measured 2 hours after the first bite of a meal. It indicates insulin sensitivity and glucose tolerance. ADA 2023: PP ≥200 mg/dL = diabetes.','FPG may be normal but PP elevated → diabetes missed. 30% of diabetes cases are detected only through PP testing. Essential for comprehensive screening and treatment evaluation.','Measure exactly 2 hours after starting to eat (not after finishing). Eat a normal meal (at least 75g carbohydrates). Note the time you started eating. No snacking in between.','<140 mg/dL = normal; 140–199 = impaired glucose tolerance; ≥200 = diabetes (ADA 2023)','mg/dL = milligrams glucose per deciliter of blood. Measures the body''s response to carbohydrate intake. 2hr PP = when glucose should return near baseline.','GCU (Sinocare)','sinocare','Chronic PP ≥200: microvascular damage (eyes, kidneys, nerves). Cardiovascular risk increases even at 140–199.','PP ≥200 mg/dL → diabetes diagnosis. PP 140–199 repeatedly → prediabetes, discuss with doctor. PP ≥300: risk of ketoacidosis.','Eat small frequent meals (3 main + 2 snacks). Complex carbs better than simple. Walk 15 minutes after meals to reduce PP by 30%.','ADA Standards of Care 2023; WHO Definition and Diagnosis of Diabetes','https://diabetesjournals.org/care/article/46/Supplement_1/S1/127039/Summary-of-Updates-Standards-of-Care-in-Diabetes');

-- ============================================================
-- cholesterolTotal
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('cholesterolTotal','id-ID','Kolesterol Total','Jumlah keseluruhan kolesterol dalam darah termasuk LDL, HDL, dan VLDL.','Kolesterol total adalah penjumlahan LDL (jahat), HDL (baik), dan VLDL. Sendiri bukan diagnosis — harus dipisahkan LDL dan HDL. Tapi sebagai skrining awal, nilai >200 menandakan perlu lipid panel lengkap (AHA/ACC 2018).','Kolesterol tinggi tidak bergejala. Plak aterosklerosis terbentuk puluhan tahun sebelum serangan jantung. Skrining setiap 5 tahun mulai usia 20 (AHA 2018).','Puasa 9–12 jam (air putih boleh). Gunakan alat point-of-care (Sinocare GCU) atau tes laboratorium. Ukur di pagi hari. Hindari olahraga berat 24 jam sebelumnya.','<200 mg/dL = diinginkan; 200–239 = borderline; ≥240 = tinggi (AHA/ACC 2018)','mg/dL = miligram kolesterol per desiliter darah. Kolesterol adalah lemak darah — dibutuhkan sel, tapi berlebih menumpuk di dinding arteri.','GCU (Sinocare)','sinocare','Total ≥240: risiko CHD 2× lipat. Aterosklerosis → serangan jantung, stroke. Plak bisa rupture → trombosis akut.','Total ≥240 atau LDL ≥160 → konsultasi dokter untuk lipid panel lengkap dan pertimbangan statin. Usia >40 + diabetes: statin indikasi.','Kurangi lemak jenuh (daging merah, mentega, kelapa). Makan serat larut (oat, kacang, buah). Olahraga naikkan HDL. Berhenti merokok naikkan HDL 10%.','AHA/ACC 2018 Cholesterol Guidelines; ATP III/NHLBI','https://www.heart.org/en/health-topics/cholesterol'),
('cholesterolTotal','en-US','Total Cholesterol','Total amount of cholesterol in blood including LDL, HDL, and VLDL.','Total cholesterol is the sum of LDL (bad), HDL (good), and VLDL. Alone it is not diagnostic — LDL and HDL must be separated. But as initial screening, >200 signals the need for a full lipid panel (AHA/ACC 2018).','High cholesterol is asymptomatic. Atherosclerotic plaque builds over decades before a heart attack. Screen every 5 years starting at age 20 (AHA 2018).','Fast 9–12 hours (water allowed). Use point-of-care device (Sinocare GCU) or lab test. Measure in the morning. Avoid heavy exercise 24 hours prior.','<200 mg/dL = desirable; 200–239 = borderline; ≥240 = high (AHA/ACC 2018)','mg/dL = milligrams cholesterol per deciliter of blood. Cholesterol is a blood fat — cells need it, but excess deposits on artery walls.','GCU (Sinocare)','sinocare','Total ≥240: 2× CHD risk. Atherosclerosis → heart attack, stroke. Plaque can rupture → acute thrombosis.','Total ≥240 or LDL ≥160 → consult doctor for full lipid panel and possible statin therapy. Age >40 + diabetes: statin indicated.','Reduce saturated fat (red meat, butter, coconut). Eat soluble fiber (oats, beans, fruit). Exercise raises HDL. Quit smoking to raise HDL by 10%.','AHA/ACC 2018 Cholesterol Guidelines; ATP III/NHLBI','https://www.heart.org/en/health-topics/cholesterol');

-- ============================================================
-- uricAcid
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('uricAcid','id-ID','Asam Urat','Produk akhir metabolisme purin — kadar tinggi menyebabkan gout dan batu ginjal.','Asam urat dibentuk dari pemecahan purin (senyawa di daging, ikan, alkohol). Ginjal membuang 70%. Kelebihan (hiperurisemia) mengkristal di sendi → gout, atau di ginjal → batu ginjal. Prevalensi gout di Indonesia 1–3% (EAU 2024).','Gout sering tidak terdiagnosis. Hiperurisemia kronis juga berkaitan dengan hipertensi, metabolic syndrome, dan penyakit ginjal kronis (MEGA study, ARA 2020).','Puasa 4 jam. Tes darah vena atau GCU point-of-care. Hindarkan makanan tinggi purin 24 jam sebelum tes (jeroan, kerang, bir). Minum air putih cukup 2L/hari sebelum tes.','Pria: <7 mg/dL; Wanita: <6 mg/dL (ACR/EULAR 2020)','mg/dL = miligram asam urat per desiliter darah. Nilai >7 = supersaturasi → kristal monosodium urat bisa terbentuk.','GCU (Sinocare)','sinocare','>7 mg/dL kronis: gout arthritis rekuren, tofi, batu ginjal urat (10–25%). Gout: risiko CKD dan kardiovaskular meningkat.','≥8 mg/dL + nyeri sendi (terutama ibu jari kaki) → reumatologis. ≥9 mg/dL tanpa gejala: diskusikan terapi urat-lowering. Batu ginjal + asam urat tinggi: urologi.','Minum air ≥2.5 L/hari. Kurangi jeroan, kerang, daging merah, bir. Konsumsi vitamin C 500 mg/hari (turunkan asam urat). Kontrol berat badan, hindari puasa ekstrem.','ACR/EULAR Gout Guidelines 2020; EAU Guidelines on Metabolic Management 2024','https://www.rheumatology.org/Practice-Quality/Clinical-Guidelines/Gout'),
('uricAcid','en-US','Uric Acid','End product of purine metabolism — high levels cause gout and kidney stones.','Uric acid is produced from purine breakdown (compounds in meat, fish, alcohol). Kidneys excrete 70%. Excess (hyperuricemia) crystals in joints → gout, or in kidneys → uric acid stones. Gout prevalence 1–3% (EAU 2024).','Gout is often underdiagnosed. Chronic hyperuricemia also links to hypertension, metabolic syndrome, and chronic kidney disease (MEGA study, ARA 2020).','Fast 4 hours. Venous blood test or GCU point-of-care. Avoid high-purine foods 24 hours before test (organ meats, shellfish, beer). Drink adequate water 2L/day prior.','Males: <7 mg/dL; Females: <6 mg/dL (ACR/EULAR 2020)','mg/dL = milligrams of uric acid per deciliter of blood. Values >7 = supersaturation → monosodium urate crystals can form.','GCU (Sinocare)','sinocare','>7 mg/dL chronic: recurrent gout arthritis, tophi, uric acid kidney stones (10–25%). Gout: increased CKD and cardiovascular risk.','≥8 mg/dL + joint pain (especially big toe) → see rheumatologist. ≥9 mg/dL without symptoms: discuss urate-lowering therapy. Kidney stones + high uric acid: see urologist.','Drink ≥2.5 L water/day. Reduce organ meats, shellfish, red meat, beer. Take vitamin C 500 mg/day (lowers uric acid). Weight control, avoid extreme fasting.','ACR/EULAR Gout Guidelines 2020; EAU Guidelines on Metabolic Management 2024','https://www.rheumatology.org/Practice-Quality/Clinical-Guidelines/Gout');

-- ============================================================
-- bodyWeight
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('bodyWeight','id-ID','Berat Badan','Massa total tubuh — dasar perhitungan BMI dan indikator risiko metabolik.','Berat badan mencakup massa lemak, otot, tulang, dan air. Fluktuasi harian 1–2 kg normal (cairan). Yang penting adalah tren jangka panjang dan komposisi (lemak vs otot). Obesitas (BMI ≥27 untuk Asia) mengobat 200+ kondisi medis (WHO).','Perubahan berat badan tak disadari bisa tanda penyakit serius: hipertiroidi, kanker, gagal jantung. Monitoring rutin mendeteksi tren naik/turun lebih awal.','Timbang di pagi hari setelah buang air, sebelum makan/siram. Pakai pakaian minimal. Timbangan di lantai datar/keras. Catat rata-rata mingguan, bukan harian.','Sesuai BMI 18.5–24.9 (umum) atau 18.5–22.9 (Asia-Pasifik, WHO 2000)','kg = kilogram massa tubuh. 1 kg ≈ 2.2 lbs. Fluktuasi harian normal: ±1–2 kg dari cairan, makanan, BAB.','Timbangan Digital','bodyScale','Obesitas (BMI ≥27 Asia): diabetes tipe 2, hipertensi, stroke, 13 jenis kanker, OA lutut, sleep apnea. Kurus (BMI <18.5): imun turun, osteoporosis.','Penurunan >5% dalam 6 bulan tanpa usaha → periksa ke dokter (tabs kanker/hipertiroidi). Kenaikan >5%/tahun → evaluasi diet dan aktivitas.','Makan sesuai porsi (metode piring: ½ sayur, ¼ protein, ¼ karbo). Catat berat mingguan. Olahraga 150 menit/minggu. Tidur 7–9 jam (kurang tidur = nafsu makan naik).','WHO Obesity Guidelines 2000; AHA Scientific Statement on Obesity 2023','https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight'),
('bodyWeight','en-US','Body Weight','Total body mass — the basis for BMI calculation and metabolic risk indicator.','Body weight includes fat, muscle, bone, and water mass. Daily fluctuation of 1–2 kg is normal (fluid). Important is long-term trend and composition (fat vs muscle). Obesity (BMI ≥27 for Asian) contributes to 200+ medical conditions (WHO).','Unintentional weight change can signal serious disease: hyperthyroidism, cancer, heart failure. Routine monitoring detects upward/downward trends earlier.','Weigh in the morning after bathroom, before eating/showering. Minimal clothing. Scale on hard flat floor. Track weekly average, not daily.','Per BMI 18.5–24.9 (general) or 18.5–22.9 (Asian-Pacific, WHO 2000)','kg = kilograms of body mass. 1 kg ≈ 2.2 lbs. Normal daily fluctuation: ±1–2 kg from fluid, food, bowel movement.','Digital Body Scale','bodyScale','Obesity (BMI ≥27 Asian): type 2 diabetes, hypertension, stroke, 13 cancer types, knee OA, sleep apnea. Underweight (BMI <18.5): weakened immunity, osteoporosis.','Loss >5% in 6 months without effort → see doctor (check cancer/hyperthyroidism). Gain >5%/year → evaluate diet and activity.','Eat proper portions (plate method: ½ vegetables, ¼ protein, ¼ carbs). Track weekly weight. Exercise 150 min/week. Sleep 7–9 hours (less sleep = increased appetite).','WHO Obesity Guidelines 2000; AHA Scientific Statement on Obesity 2023','https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight');

-- ============================================================
-- bmi
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('bmi','id-ID','BMI','Body Mass Index — rasio berat terhadap tinggi kuadrat sebagai indikator risiko metabolik.','BMI = berat (kg) ÷ tinggi² (m²). Tidak membedakan lemak dan otot — atlet bisa BMI tinggi tapi sehat. Klasifikasi Asia-Pasifik (WHO 2000): normal 18.5–22.9, overweight 23–24.9, obesitas ≥25. Untuk Indonesia, Kemenkes menggunakan ≥27 sebagai obesitas.','BMI adalah skrining cepat pertama — bukan diagnosis. Tapi BMI ≥27 (Asia) berkorelasi kuat dengan risiko diabetes 2, hipertensi, dan dislipidemia. Data Riskesdas: obesitas Indonesia 35.4%.','Ukur berat badan dan tinggi badan secara akurat. Tinggi: tanpa sepatu, berdiri tegak. Berat: pagi hari, pakaian minimal. BMI dihitung otomatis oleh aplikasi.','18.5–22.9 = normal (Asia); 23–24.9 = overweight; 25–29.9 = obesitas I; ≥30 = obesitas II (WHO Asia-Pasifik 2000)','kg/m² = kilogram per meter persegi. Contoh: berat 70 kg, tinggi 1.70 m → BMI = 70/(1.70)² = 24.2. Artinya, 24.2 kg massa tersebar di setiap m² permukaan tubuh.','Dihitung Otomatis','calculated','BMI ≥27: risiko diabetes 2, hipertensi, stroke, 13 kanker naik 2–3×. BMI <18.5: malnutrisi, imun turun, osteoporosis, anemia.','BMI ≥30 atau lingkar perut pria ≥90/wanita ≥80 → konsultasi dokter untuk evaluasi metabolik lengkap. BMI <17 → malnutrisi perlu intervensi.','Target berat realistis: turun 5–10% dari berat awal sudah bermakna klinis. Jangan diet ketat >1 kg/minggu. Fokus pola makan sehat jangka panjang, bukan diet kilat.','WHO Asia-Pacific BMI Classification 2000; Kemenkes RI Riskesdas 2023','https://www.who.int/publications/i/item/9241208943'),
('bmi','en-US','BMI','Body Mass Index — weight-to-height squared ratio as a metabolic risk indicator.','BMI = weight (kg) ÷ height² (m²). It does not distinguish fat from muscle — athletes can have high BMI while being healthy. Asian-Pacific classification (WHO 2000): normal 18.5–22.9, overweight 23–24.9, obesity ≥25.','BMI is a quick first screening — not a diagnosis. But BMI ≥27 (Asian) strongly correlates with diabetes 2, hypertension, and dyslipidemia risk. Data Riskesdas: Indonesia obesity 35.4%.','Accurately measure weight and height. Height: without shoes, standing straight. Weight: morning, minimal clothing. BMI calculated automatically by the app.','18.5–22.9 = normal (Asian); 23–24.9 = overweight; 25–29.9 = obesity I; ≥30 = obesity II (WHO Asia-Pacific 2000)','kg/m² = kilograms per square meter. Example: weight 70 kg, height 1.70 m → BMI = 70/(1.70)² = 24.2. This means 24.2 kg mass per m² of body surface.','Auto-calculated','calculated','BMI ≥27: type 2 diabetes, hypertension, stroke risk, 13 cancers 2–3× higher. BMI <18.5: malnutrition, weakened immunity, osteoporosis, anemia.','BMI ≥30 or waist circumference male ≥90/female ≥80 → see doctor for full metabolic evaluation. BMI <17 → malnutrition requiring intervention.','Realistic target: losing 5–10% of initial weight is clinically meaningful. Don''t crash diet >1 kg/week. Focus on long-term healthy eating, not quick diets.','WHO Asia-Pacific BMI Classification 2000; Kemenkes RI Riskesdas 2023','https://www.who.int/publications/i/item/9241208943');

-- ============================================================
-- waistCircumference
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('waistCircumference','id-ID','Lingkar Perut','Ukuran lemak viseral di perut — prediktor risiko metabolik independen dari BMI.','Lingkar perut mengukur lemak di rongga perut (viseral). Lemak viseral lebih berbahaya dari lemak bawah kulit — aktif melepaskan sitokin inflamasi yang menyebabkan resistensi insulin, hipertensi, dan dislipidemia. IDF 2023: lingkar perut adalah komponen wajib diagnosis metabolik syndrome.','Banyak orang BMI normal tapi lingkar perut besar (normal weight obesity). Risiko metabolik tinggi = lingkar perut besar, BUKAN sekadar BMI tinggi. IDF 2023 menetapkan cutoff Asia: pria ≥90, wanita ≥80.','Berdiri tegak, perut rileks (jangan kempeskan). Meteran di titik tengah antara tulang rusuk terbawah dan puncak tulang pinggang (iliac crest). Ukur di akhir napas normal. Jangan kencangkan meteran.','Pria <90 cm, Wanita <80 cm (IDF Asia 2023). Pria ≥90, Wanita ≥80 = risiko metabolik tinggi.','cm = sentimeter keliling perut pada titik tengah antara iga terakhir dan tulang pinggang. Mengukur lemak intra-abdominal, bukan lemak kulit.','Meteran','manual','Lingkar perut ≥90 (pria)/≥80 (wanita): 3× risiko diabetes tipe 2, 2× risiko hipertensi. MetS: risiko kardiovaskular 2–3× lipat.','Lingkar perut ≥100 (pria)/≥90 (wanita) → evaluasi代谢 syndrome lengkap (gula darah, lipid, tekanan darah). Kombinasi BMI ≥23 + perut besar → risiko sangat tinggi.','Kurangi gula fruktosa (minuman manis, sirup) — paling mudah disimpan sebagai lemak viseral. Olahraga aerobik 150 menit/minggu membakar lemak viseral. Latihan bebas beban tidak cukup — butuh kardio.','IDF Consensus Worldwide Definition of Metabolic Syndrome 2023; WHO','https://www.idf.org/e-library/consensus-statements/60-idfconsensus-worldwide-definitionof-the-metabolic-syndrome'),
('waistCircumference','en-US','Waist Circumference','Measures visceral fat in the abdomen — an independent metabolic risk predictor from BMI.','Waist circumference measures fat in the abdominal cavity (visceral). Visceral fat is more dangerous than subcutaneous fat — it actively releases inflammatory cytokines causing insulin resistance, hypertension, and dyslipidemia. IDF 2023: waist circumference is mandatory for metabolic syndrome diagnosis.','Many people have normal BMI but large waist (normal weight obesity). High metabolic risk = large waist, NOT just high BMI. IDF 2023 sets Asian cutoffs: male ≥90, female ≥80.','Stand straight, abdomen relaxed (do not suck in). Tape at midpoint between lowest rib and top of hip bone (iliac crest). Measure at end of normal exhale. Do not pull tape tight.','Male <90 cm, Female <80 cm (IDF Asia 2023). Male ≥90, Female ≥80 = high metabolic risk.','cm = centimeters of waist circumference at the midpoint between the lowest rib and hip bone. Measures intra-abdominal fat, not skin fat.','Measuring Tape','manual','Waist ≥90 (male)/≥80 (female): 3× type 2 diabetes risk, 2× hypertension risk. MetS: 2–3× cardiovascular risk.','Waist ≥100 (male)/≥90 (female) → full metabolic syndrome evaluation (glucose, lipids, blood pressure). BMI ≥23 + large waist → very high risk.','Reduce fructose sugar (sugary drinks, syrup) — most easily stored as visceral fat. Aerobic exercise 150 min/week burns visceral fat. Weight training alone is not enough — cardio needed.','IDF Consensus Worldwide Definition of Metabolic Syndrome 2023; WHO','https://www.idf.org/e-library/consensus-statements/60-idfconsensus-worldwide-definitionof-the-metabolic-syndrome');

-- ============================================================
-- bodyTemperature
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('bodyTemperature','id-ID','Suhu Tubuh','Suhu inti tubuh — indikator infeksi, inflamasi, dan status metabolik.','Suhu inti diatur oleh hipotalamus pada set point ~37°C. Demam (≥37.5°C aksila atau ≥38.0°C rektal) = tanda pertahanan tubuh melawan infeksi. Hipotermia (<35°C) = darurat medis. Fluktuasi harian 0.5°C normal (pagi rendah, sore tinggi).','Demam adalah tanda paling sensitif dari infeksi sistemik. Dalam konteks pasca-bedah atau imunokompromai, demam ringan sudah bisa tanda sepsis. Hipotermia pada lansia bisa tandanya hipotiroidi atau sepsis.','Termometer digital di ketiak: 5 menit, lengan rapat ke tubuh. Termometer telingan: tarik daun telinga ke atas-belakang (dewasa). Hindari ukur setelah mandi/berolahraga (tunggu 30 menit). Jangan ukur setelah minum panas/dingin.','36.1–37.2°C (ketiak); 36.5–37.5°C (rektal). Demam: ≥37.5°C (ketiak) atau ≥38.0°C (rektal).','°C = derajat Celsius. 37°C = set point normal hipotalamus. 1°C di atas normal = demam ringan; 2°C = demam sedang; >3°C = demam tinggi.','Termometer Digital','thermometer','Demam berkepanjangan: infeksi kronis (TB, endokarditis), malignansi, penyakit autoimun. >40°C: risiko kejang demam (anak), kerusakan protein. <35°C: aritmia, gagal organ.','≥39.5°C (dewasa) atau ≥40°C (anak) → segera ke IGD. Demam >3 hari tanpa sebab jelas → dokter. <35°C → IGD. Demam + leher kaku + ruam → IGD (septikemia/meningitis).','Istirahat cukup saat demam. Minum air ≥2.5 L/hari. Kompres hangat (bukan dingin) untuk menurunkan demam. Jangan pakai paracetamol jika demam <38.5°C tanpa ketidaknyamanan.','Mayo Clinic Body Temperature; WHO Clinical Management of Severe Infection 2022','https://www.mayoclinic.org/tests-procedures/thermometry/about/pac-20391972'),
('bodyTemperature','en-US','Body Temperature','Core body temperature — indicator of infection, inflammation, and metabolic status.','Core temperature is regulated by the hypothalamus at a set point of ~37°C. Fever (≥37.5°C axillary or ≥38.0°C rectal) = sign that the body is fighting infection. Hypothermia (<35°C) = medical emergency. Daily fluctuation of 0.5°C is normal (lower in morning, higher in evening).','Fever is the most sensitive sign of systemic infection. In post-surgical or immunocompromised patients, even mild fever can indicate sepsis. Hypothermia in elderly may indicate hypothyroidism or sepsis.','Digital thermometer in armpit: 5 minutes, arm close to body. Ear thermometer: pull ear upward-backward (adults). Avoid measuring after bathing/exercise (wait 30 min). Don''t measure after drinking hot/cold fluids.','36.1–37.2°C (axillary); 36.5–37.5°C (rectal). Fever: ≥37.5°C (axillary) or ≥38.0°C (rectal).','°C = degrees Celsius. 37°C = normal hypothalamic set point. 1°C above normal = low-grade fever; 2°C = moderate; >3°C = high fever.','Digital Thermometer','thermometer','Prolonged fever: chronic infections (TB, endocarditis), malignancy, autoimmune disease. >40°C: febrile seizure risk (children), protein damage. <35°C: arrhythmia, organ failure.','≥39.5°C (adults) or ≥40°C (children) → go to ER immediately. Fever >3 days without clear cause → see doctor. <35°C → ER. Fever + stiff neck + rash → ER (septicemia/meningitis).','Rest adequately during fever. Drink ≥2.5 L water/day. Warm (not cold) compress to reduce fever. Avoid paracetamol if fever <38.5°C without discomfort.','Mayo Clinic Body Temperature; WHO Clinical Management of Severe Infection 2022','https://www.mayoclinic.org/tests-procedures/thermometry/about/pac-20391972');

-- ============================================================
-- sleepDuration
-- ============================================================
INSERT INTO HL_medicalTermPopups (termCode,locale,label,shortDef,fullDef,whyMeasure,howToMeasure,normalRange,unitExplanation,deviceName,deviceTypeCode,risksIfAbnormal,whenToSeeDoctor,preventionTip,sourceName,sourceUrl) VALUES
('sleepDuration','id-ID','Durasi Tidur','Lamanya tidur per malam — pilar kesehatan seiring nutrisi dan olahraga.','Durasi tidur mengukur total waktu tidur nyata (bukan waktu di tempat tidur). Tidur <7 jam kronis: 26% risiko kematian lebih tinggi, 33% lebih banyak pilek (Cohen 2009), 48% lebih banyak penyakit jantung (AHA 2023). AASM 2023 merekomendasikan 7–9 jam untuk dewasa.','Tidur pendek kronis = faktor risiko independen untuk obesitas, diabetes tipe 2, hipertensi, depresi, dan kanker. Konsensus AASM 2023: tidur cukup = vital sign ke-5 selain tekanan darah, nadi, suhu, dan pernapasan.','Catat waktu tidur dan bangun aktual (bukan waktu tidur dan bangun di tempat tidur). Gunakan sleep tracker jika tersedia. Rata-rata 7 hari lebih akurat dari 1 malam. Hindari kafein 6 jam sebelum tidur.','7–9 jam per malam (dewasa 18–64); 7–8 jam (≥65 tahun) — AASM/AHA 2023','jam = durasi tidur aktual dalam jam. Bukan waktu di tempat tidur. 7.5 jam artinya tertidur 7 jam 30 menit (bukan 7 jam 30 menit di kasur).','Sleep Tracker','sleepTracker','<6 jam kronis: obesitas 55%, diabetes 28%, hipertensi 33%, depresi 2× lipat. >9 jam kronis: bisa tandanya sleep apnea, depresi, hipotiroidi.','Insomnia >3 malam/minggu selama >3 bulan → konsultasi dokter tidur. Mendengkur keras + kantuk siang → skrining sleep apnea. Bangun terengah-engah → IGD jika berulang.','Tidur bangun pada jam sama setiap hari (termasuk weekend). Kamar gelap, sejuk (18–20°C), tenang. Layar off 30–60 menit sebelum tidur (cahaya biru). Caffeine cutoff 14.00.','AASM Sleep Duration Recommendations 2023; AHA Life''s Essential 8 2023','https://aasm.org/clinical-resources/sleep-duration-recommendations/'),
('sleepDuration','en-US','Sleep Duration','Length of sleep per night — a health pillar on par with nutrition and exercise.','Sleep duration measures actual sleep time (not time in bed). Chronic short sleep <7hr: 26% higher mortality, 33% more colds (Cohen 2009), 48% more heart disease (AHA 2023). AASM 2023 recommends 7–9 hours for adults.','Chronic short sleep = independent risk factor for obesity, type 2 diabetes, hypertension, depression, and cancer. AASM 2023 consensus: adequate sleep = 5th vital sign alongside BP, pulse, temperature, and respiration.','Record actual sleep and wake times (not time in bed asleep). Use sleep tracker if available. 7-day average is more accurate than 1 night. Avoid caffeine 6 hours before sleep.','7–9 hours per night (adults 18–64); 7–8 hours (≥65 years) — AASM/AHA 2023','hours = actual sleep duration in hours. Not time in bed. 7.5 hours means asleep for 7 hours 30 minutes (not in bed for 7h30m).','Sleep Tracker','sleepTracker','<6 hours chronic: obesity 55%, diabetes 28%, hypertension 33%, depression 2×. >9 hours chronic: may indicate sleep apnea, depression, hypothyroidism.','Insomnia >3 nights/week for >3 months → consult sleep doctor. Loud snoring + daytime sleepiness → screen for sleep apnea. Waking gasping → ER if recurrent.','Same sleep/wake time every day (including weekends). Dark, cool (18–20°C), quiet room. Screens off 30–60 min before sleep (blue light). Caffeine cutoff at 2 PM.','AASM Sleep Duration Recommendations 2023; AHA Life''s Essential 8 2023','https://aasm.org/clinical-resources/sleep-duration-recommendations/');
